//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyExchangeWpfClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetExchangeRate", ReplyAction="http://tempuri.org/IService1/GetExchangeRateResponse")]
        decimal GetExchangeRate(string currencyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetExchangeRate", ReplyAction="http://tempuri.org/IService1/GetExchangeRateResponse")]
        System.Threading.Tasks.Task<decimal> GetExchangeRateAsync(string currencyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConvertToPln", ReplyAction="http://tempuri.org/IService1/ConvertToPlnResponse")]
        decimal ConvertToPln(decimal amount, string currencyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConvertToPln", ReplyAction="http://tempuri.org/IService1/ConvertToPlnResponse")]
        System.Threading.Tasks.Task<decimal> ConvertToPlnAsync(decimal amount, string currencyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConvertFromPln", ReplyAction="http://tempuri.org/IService1/ConvertFromPlnResponse")]
        decimal ConvertFromPln(decimal amount, string currencyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConvertFromPln", ReplyAction="http://tempuri.org/IService1/ConvertFromPlnResponse")]
        System.Threading.Tasks.Task<decimal> ConvertFromPlnAsync(decimal amount, string currencyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConvertCurrency", ReplyAction="http://tempuri.org/IService1/ConvertCurrencyResponse")]
        decimal ConvertCurrency(decimal amount, string fromCurrency, string toCurrency);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConvertCurrency", ReplyAction="http://tempuri.org/IService1/ConvertCurrencyResponse")]
        System.Threading.Tasks.Task<decimal> ConvertCurrencyAsync(decimal amount, string fromCurrency, string toCurrency);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateUser", ReplyAction="http://tempuri.org/IService1/CreateUserResponse")]
        void CreateUser(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateUser", ReplyAction="http://tempuri.org/IService1/CreateUserResponse")]
        System.Threading.Tasks.Task CreateUserAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBalances", ReplyAction="http://tempuri.org/IService1/GetBalancesResponse")]
        string GetBalances(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBalances", ReplyAction="http://tempuri.org/IService1/GetBalancesResponse")]
        System.Threading.Tasks.Task<string> GetBalancesAsync(int userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : CurrencyExchangeWpfClient.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<CurrencyExchangeWpfClient.ServiceReference1.IService1>, CurrencyExchangeWpfClient.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal GetExchangeRate(string currencyCode) {
            return base.Channel.GetExchangeRate(currencyCode);
        }
        
        public System.Threading.Tasks.Task<decimal> GetExchangeRateAsync(string currencyCode) {
            return base.Channel.GetExchangeRateAsync(currencyCode);
        }
        
        public decimal ConvertToPln(decimal amount, string currencyCode) {
            return base.Channel.ConvertToPln(amount, currencyCode);
        }
        
        public System.Threading.Tasks.Task<decimal> ConvertToPlnAsync(decimal amount, string currencyCode) {
            return base.Channel.ConvertToPlnAsync(amount, currencyCode);
        }
        
        public decimal ConvertFromPln(decimal amount, string currencyCode) {
            return base.Channel.ConvertFromPln(amount, currencyCode);
        }
        
        public System.Threading.Tasks.Task<decimal> ConvertFromPlnAsync(decimal amount, string currencyCode) {
            return base.Channel.ConvertFromPlnAsync(amount, currencyCode);
        }
        
        public decimal ConvertCurrency(decimal amount, string fromCurrency, string toCurrency) {
            return base.Channel.ConvertCurrency(amount, fromCurrency, toCurrency);
        }
        
        public System.Threading.Tasks.Task<decimal> ConvertCurrencyAsync(decimal amount, string fromCurrency, string toCurrency) {
            return base.Channel.ConvertCurrencyAsync(amount, fromCurrency, toCurrency);
        }
        
        public void CreateUser(string username) {
            base.Channel.CreateUser(username);
        }
        
        public System.Threading.Tasks.Task CreateUserAsync(string username) {
            return base.Channel.CreateUserAsync(username);
        }
        
        public string GetBalances(int userId) {
            return base.Channel.GetBalances(userId);
        }
        
        public System.Threading.Tasks.Task<string> GetBalancesAsync(int userId) {
            return base.Channel.GetBalancesAsync(userId);
        }
    }
}
